INSERT INTO catalog_components (code, component_name, description, is_active)
VALUES
  ('ENGINE', 'ENGINE', NULL, 1),
  ('UNDERCARRIAGE', 'UNDERCARRIAGE', NULL, 1),
  ('ELECTRICAL', 'ELECTRICAL', NULL, 1),
  ('BODY', 'BODY', NULL, 1),
  ('INTERIOR', 'INTERIOR', NULL, 1)
ON DUPLICATE KEY UPDATE
  component_name = VALUES(component_name),
  description = VALUES(description),
  is_active = VALUES(is_active),
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO catalog_panels (component_id, panel_name)
SELECT cc.id, seed.panel_name
FROM (
  SELECT 'BODY' AS component_code, 'FRONT BUMPER' AS panel_name
  UNION ALL SELECT 'BODY', 'REAR BUMPER'
  UNION ALL SELECT 'BODY', 'FRONT FENDER LH'
  UNION ALL SELECT 'BODY', 'FRONT FENDER RH'
  UNION ALL SELECT 'BODY', 'FRONT DOOR LH'
  UNION ALL SELECT 'BODY', 'FRONT DOOR RH'
  UNION ALL SELECT 'BODY', 'REAR DOOR LH'
  UNION ALL SELECT 'BODY', 'REAR DOOR RH'
  UNION ALL SELECT 'BODY', 'HOOD'
  UNION ALL SELECT 'BODY', 'TRUNK LID'
  UNION ALL SELECT 'ENGINE', 'ENGINE ASSEMBLY'
  UNION ALL SELECT 'ENGINE', 'COOLING SYSTEM'
  UNION ALL SELECT 'ENGINE', 'FUEL SYSTEM'
  UNION ALL SELECT 'ENGINE', 'INTAKE SYSTEM'
  UNION ALL SELECT 'ENGINE', 'EXHAUST SYSTEM'
  UNION ALL SELECT 'UNDERCARRIAGE', 'FRONT SUSPENSION'
  UNION ALL SELECT 'UNDERCARRIAGE', 'REAR SUSPENSION'
  UNION ALL SELECT 'UNDERCARRIAGE', 'BRAKE SYSTEM'
  UNION ALL SELECT 'UNDERCARRIAGE', 'STEERING SYSTEM'
  UNION ALL SELECT 'UNDERCARRIAGE', 'TRANSMISSION'
  UNION ALL SELECT 'ELECTRICAL', 'MAIN WIRING'
  UNION ALL SELECT 'ELECTRICAL', 'LIGHTING'
  UNION ALL SELECT 'ELECTRICAL', 'INSTRUMENT PANEL'
  UNION ALL SELECT 'ELECTRICAL', 'STARTING SYSTEM'
  UNION ALL SELECT 'ELECTRICAL', 'CHARGING SYSTEM'
  UNION ALL SELECT 'ELECTRICAL', 'WIPER SYSTEM'
  UNION ALL SELECT 'INTERIOR', 'DASHBOARD'
  UNION ALL SELECT 'INTERIOR', 'FRONT SEAT'
  UNION ALL SELECT 'INTERIOR', 'REAR SEAT'
  UNION ALL SELECT 'INTERIOR', 'DOOR TRIM LH'
  UNION ALL SELECT 'INTERIOR', 'DOOR TRIM RH'
  UNION ALL SELECT 'INTERIOR', 'HEADLINER'
  UNION ALL SELECT 'INTERIOR', 'CARPET'
  UNION ALL SELECT 'INTERIOR', 'CENTER CONSOLE'
) AS seed
JOIN catalog_components cc ON cc.code = seed.component_code
ON DUPLICATE KEY UPDATE
  updated_at = CURRENT_TIMESTAMP;
