CREATE TABLE IF NOT EXISTS sm_issue_log (
  id VARCHAR(36) NOT NULL,
  issue_number VARCHAR(50) NOT NULL,
  source_type ENUM('QC_REJECT', 'WORK_LEDGER', 'MANUAL') NOT NULL DEFAULT 'MANUAL',
  source_ref_id VARCHAR(36) DEFAULT NULL,
  car_id VARCHAR(36) NOT NULL,
  division_id INT DEFAULT NULL,
  countdown_id VARCHAR(36) DEFAULT NULL,
  plan_id VARCHAR(36) DEFAULT NULL,
  qc_id VARCHAR(36) DEFAULT NULL,
  ledger_id VARCHAR(36) DEFAULT NULL,
  issue_type VARCHAR(50) NOT NULL,
  severity ENUM('LOW', 'MEDIUM', 'HIGH') NOT NULL DEFAULT 'LOW',
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  status ENUM('OPEN', 'ACKNOWLEDGED', 'IN_PROGRESS', 'QC_RECHECK', 'RESOLVED', 'ESCALATED', 'WAIVED') NOT NULL DEFAULT 'OPEN',
  is_urgent TINYINT(1) NOT NULL DEFAULT 0,
  reported_by VARCHAR(50) DEFAULT NULL,
  reported_by_name VARCHAR(100) DEFAULT NULL,
  assigned_to VARCHAR(50) DEFAULT NULL,
  assigned_to_name VARCHAR(100) DEFAULT NULL,
  acknowledged_by VARCHAR(50) DEFAULT NULL,
  acknowledged_at TIMESTAMP NULL DEFAULT NULL,
  escalated_by VARCHAR(50) DEFAULT NULL,
  escalated_at TIMESTAMP NULL DEFAULT NULL,
  resolved_by VARCHAR(50) DEFAULT NULL,
  resolved_at TIMESTAMP NULL DEFAULT NULL,
  resolution_notes TEXT DEFAULT NULL,
  waived_by VARCHAR(50) DEFAULT NULL,
  waived_at TIMESTAMP NULL DEFAULT NULL,
  waive_notes TEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_issue_number (issue_number),
  UNIQUE KEY uk_issue_source (source_type, source_ref_id),
  KEY idx_issue_car_status (car_id, status),
  KEY idx_issue_division_status (division_id, status),
  KEY idx_issue_severity_status (severity, status),
  KEY idx_issue_countdown (countdown_id),
  KEY idx_issue_plan (plan_id),
  KEY idx_issue_qc (qc_id),
  KEY idx_issue_ledger (ledger_id),
  CONSTRAINT fk_issue_car FOREIGN KEY (car_id) REFERENCES cars (id) ON DELETE RESTRICT,
  CONSTRAINT fk_issue_division FOREIGN KEY (division_id) REFERENCES sm_divisi (id) ON DELETE SET NULL,
  CONSTRAINT fk_issue_countdown FOREIGN KEY (countdown_id) REFERENCES sm_jobdesc_countdown (id) ON DELETE SET NULL,
  CONSTRAINT fk_issue_plan FOREIGN KEY (plan_id) REFERENCES sm_jobdesc_plan (id) ON DELETE SET NULL,
  CONSTRAINT fk_issue_qc FOREIGN KEY (qc_id) REFERENCES sm_qc_inspections (id) ON DELETE SET NULL,
  CONSTRAINT fk_issue_ledger FOREIGN KEY (ledger_id) REFERENCES sm_work_ledger (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS sm_weekly_work_config (
  id VARCHAR(36) NOT NULL,
  week_start_date DATE NOT NULL,
  weekday_hours FLOAT NOT NULL DEFAULT 8,
  saturday_hours FLOAT NOT NULL DEFAULT 5,
  sunday_hours FLOAT NOT NULL DEFAULT 0,
  weekday_overtime_hours FLOAT NOT NULL DEFAULT 5,
  saturday_overtime_hours FLOAT NOT NULL DEFAULT 3,
  sunday_overtime_hours FLOAT NOT NULL DEFAULT 0,
  efficiency_factor FLOAT NOT NULL DEFAULT 1,
  qc_buffer_days INT NOT NULL DEFAULT 1,
  created_by VARCHAR(50) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_week_start_date (week_start_date)
);
