CREATE TABLE IF NOT EXISTS `sms_db`.`sm_bubut_invoice` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `invoice_no` VARCHAR(64) NOT NULL,
  `invoice_type` ENUM('DIREKSI', 'CUSTOMER') NOT NULL,
  `status` ENUM('RELEASED', 'CANCELLED') NOT NULL DEFAULT 'RELEASED',
  `active_invoice_key` VARCHAR(128) NULL,
  `sales_invoice_date` DATE NOT NULL,
  `wo_date` DATE NULL,
  `source_wo_id` VARCHAR(64) NULL,
  `source_wob_no` VARCHAR(64) NULL,
  `head_project_name` VARCHAR(160) NULL,
  `po_no` VARCHAR(128) NULL,
  `po_date` DATE NULL,
  `car_id` VARCHAR(64) NULL,
  `car_type` VARCHAR(255) NULL,
  `sparepart_name` VARCHAR(255) NULL,
  `qty` DECIMAL(12,2) NULL,
  `qty_unit` VARCHAR(32) NULL,
  `operator_name` VARCHAR(160) NULL,
  `division_name` VARCHAR(160) NULL,
  `total_work_minutes` INT NOT NULL DEFAULT 0,
  `total_work_hour_text` VARCHAR(32) NULL,
  `total_work_hour_decimal` DECIMAL(12,4) NOT NULL DEFAULT 0,
  `power_watt` DECIMAL(12,2) NOT NULL DEFAULT 7500,
  `power_cost_kwh` DECIMAL(12,2) NOT NULL DEFAULT 1444,
  `working_hour_total` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `material_total` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `total_price_bubut` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `markup_percent` DECIMAL(8,2) NOT NULL DEFAULT 235.00,
  `markup_multiplier` DECIMAL(8,4) NOT NULL DEFAULT 3.3500,
  `price_after_markup` DECIMAL(18,2) NULL,
  `rounding_step` INT NOT NULL DEFAULT 1000,
  `price_rounding` DECIMAL(18,2) NULL,
  `material_use_json` JSON NULL,
  `working_hours_json` JSON NULL,
  `picture_urls_json` JSON NULL,
  `process_detail_text` TEXT NULL,
  `source_snapshot_json` JSON NULL,
  `released_by` VARCHAR(64) NOT NULL,
  `released_by_name` VARCHAR(160) NULL,
  `released_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `printed_count` INT NOT NULL DEFAULT 0,
  `last_printed_at` DATETIME NULL,
  `cancelled_by` VARCHAR(64) NULL,
  `cancelled_by_name` VARCHAR(160) NULL,
  `cancelled_at` DATETIME NULL,
  `cancel_reason` TEXT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_sm_bubut_invoice_no` (`invoice_no`),
  UNIQUE KEY `uq_sm_bubut_invoice_active_key` (`active_invoice_key`),
  KEY `idx_sm_bubut_invoice_source_wob` (`source_wob_no`),
  KEY `idx_sm_bubut_invoice_source_wo` (`source_wo_id`),
  KEY `idx_sm_bubut_invoice_type_status` (`invoice_type`, `status`),
  KEY `idx_sm_bubut_invoice_sales_date` (`sales_invoice_date`),
  KEY `idx_sm_bubut_invoice_car` (`car_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
